version: '3.1'

services:
  jenkins:
    # build: jenkins_casc/
    image: my-jenkins
    ports:
      - "50000:50000"
      - "8085:8080"
    volumes:
      - type: volume
          source: jenkins-volume
          target: /var/jenkins_home
      - type: bind
          source: $PWD/jenkins_casc/casc_config/casc.yml
          target: /var/jenkins_home/casc.yml
      - type: bind
          source: $PWD/jenkins_casc/casc_config/seedjob.groovy
          target: /var/jenkins_home/seedjob.groovy

volumes:
  jenkins-volume:
    external: false