version: '3'

name: my-project

services:

  docker:
    build: docker_environment/
    image: env-docker
    container_name: env-docker
    volumes:
    - type: bind
      source: /var/run/docker.sock
      target: /var/run/docker.sock
  
  registry:
    image: registry:2
    container_name: registry
    restart: always
    ports:
    - "5000:5000"
  
  jenkins:
    build: jenkins_casc/
    image: casc-jenkins
    container_name: jenkins
    restart: always
    ports:
    - "50000:50000"
    - "8085:8080"
    volumes:
    - type: volume
      source: jenkins-volume
      target: /var/jenkins_home
    - type: bind
      source: $PWD/jenkins_casc/casc_config/casc.yml
      target: /var/jenkins_home/casc.yml
    - type: bind
      source: $PWD/jenkins_casc/casc_config/jobs
      target: /usr/local/jobs
    env_file:
    - ../.env
    environment:
    - TEST=${TEST}
  
volumes:
  jenkins-volume: