version: '3'
name: my-project
services:
  jenkins:
    # build: jenkins_casc/
    image: my-jenkins
    container_name: jenkins
    ports:
      - "50000:50000"
      - "8085:8080"
    volumes:
      - type: volume
          source: jenkins-volume
          target: /var/jenkins_home
      - type: bind
          source: $PWD/jenkins_casc/casc_config/casc.yml
          target: /var/jenkins_home/casc.yml
      - type: bind
          source: $PWD/jenkins_casc/casc_config/seedjob.groovy
          target: /usr/local/seedjob.groovy
    environment:
    - JENKINS_ADMIN_ID=${JENKINS_ADMIN_ID}
    - JENKINS_ADMIN_PASSWD=${JENKINS_ADMIN_PASSWD}
    - DOCKER_HOST_IP=${DOCKER_HOST_IP}
    - DOCKER_NODE_USER=${DOCKER_NODE_USER}
    - DOCKER_NODE_PASSWD=${DOCKER_NODE_PASSWD}
    - AGENT_USER=${AGENT_USER}
    - AGENT_PASSWD=${AGENT_PASSWD}
    - GITHUB_USER=${GITHUB_USER}
    - GITHUB_TOKEN=${GITHUB_TOKEN}

volumes:
  jenkins-volume: