jenkins:
  securityRealm:
    local:
      allowsSignup: false
      users:
       - id: ${JENKINS_ADMIN_ID}
         password: ${JENKINS_ADMIN_PASSWD}
       - id: guest
         password: guest
  authorizationStrategy:
    globalMatrix:
      permissions:
        - "Overall/Administer:${JENKINS_ADMIN_ID}"
        - "Overall/Read:authenticated"
        - "Job/Build:guest"
        - "Job/Cancel:guest"
        - "Job/Read:guest"
        - "Job/Workspace:guest"
        - "Run/Replay:guest"
        - "Run/Update:guest"
  # make sure our jenkins master has 1 executor
  # so that we can run our pipelines
  numExecutors: 1
  disableRememberMe: true
  markupFormatter:
    rawHtml:
      disableSyntaxHighlighting: false
  # Setup the nodes for pipelines
  nodes:
  - permanent:
      # Setup the node docker
      labelString: "dockerHost linux rocky"
      launcher:
        ssh:
          credentialsId: "docker-host-credentials"
          # Using jenkins in docker the node should always be this one
          # Not if there is a remote server with docker
          host: ${DOCKER_HOST_IP}
          port: 22
          sshHostKeyVerificationStrategy: "nonVerifyingKeyVerificationStrategy"
      name: "docker-host"
      remoteFS: "/home/${DOCKER_NODE_USER}/jenkins_dir"
      retentionStrategy: "always"
  # Setup the cloud docker
  clouds:
  - docker:
      containerCap: 3
      dockerApi:
        connectTimeout: 60
        dockerHost:
          uri: "tcp://${DOCKER_HOST_IP}:4243"
        readTimeout: 60
      name: "docker"
      templates:
      - connector:
          ssh:
            sshKeyStrategy:
              manuallyConfiguredSSHKey:
                credentialsId: "agent-credentials"
                sshHostKeyVerificationStrategy: "nonVerifyingKeyVerificationStrategy"
        dockerTemplateBase:
          cpuPeriod: 0
          cpuQuota: 0
          image: "rocky-agent:latest"
        labelString: "dockerAgent container rocky linux"
        name: "docker-agent"
        pullStrategy: PULL_NEVER
        pullTimeout: 300
        remoteFs: "/home/jenkins"
# Variety of settings
unclassified:
  # Setup english as language whatever the browser language
  locale:
    ignoreAcceptLanguage: true
    systemLocale: "english"
  location:
    adminAddress: "sofa.kreutz@yahoo.fr"
    url: "http://localhost:8088/"
# Credentials
credentials:
  system:
    domainCredentials:
    - credentials:
      - usernamePassword:
          # Credentials for the node docker
          description: "docker node"
          id: "docker-host-credentials"
          password: ${DOCKER_NODE_PASSWD}
          scope: GLOBAL
          username: ${DOCKER_NODE_USER}
      - usernamePassword:
          description: "rocky agent"
          id: "agent-credentials"
          password: "${AGENT_PASSWD}"
          scope: GLOBAL
          username: "${AGENT_USER}"
# specify the seedjob groovy script that will create the  pipelines for us
jobs:
  - file: /usr/local/seedjob.groovy